spring:
  application:
    name: config-server
  security:
    user:
      name: admin
      password: 123456789
      roles: ADMIN

  cloud:
    config:
      server:
        git:
          uri: https://github.com/damianPolchlopek/PhotoAppConfiguration
#          username:
#          password:
          clone-on-start: true
          default-label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

my-spring:
  security:
    user:
      name: client
      password: 123456789
      roles: CLIENT

server:
  port: 8012

encrypt:
  key: mojsekretnyklucz

debug: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health

