spring:
  application:
    name: user-ws
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  cloud:
    config:
      username: client
      password: 123456789
  config:
    import: "configserver:http://localhost:8012"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

albums:
  url: http://albums-ws/users/%s/albums

logging:
  level:
    org:
      example:
        photoappapiusers:
          data:
            AlbumsServiceClient: DEBUG
          service:
            UserService: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: users-ws.log


management:
  endpoints:
    web:
      exposure:
        include: health, management, actuator, circuitbreakerevents
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      albums-ws:
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        minimum-number-of-calls: 5
        consumer-buffer-size: 10

  retry:
    retry-aspect-order: 2
    instances:
      albums-ws:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5
