spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8012"

  cloud:
    config:
      username: client
      password: 123456789
    gateway:
      routes:
        - id: user-ws-checker
          uri: lb://user-ws
          predicates:
            - Path=/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: user-ws-get
          uri: lb://user-ws
          predicates:
            - Path=/users/**
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
#            - StripPrefix=1

        - id: users-ws-actuator
          uri: lb://user-ws
          predicates:
            - Path=/users-ws/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1

        - id: users-ws-login
          uri: lb://user-ws
          predicates:
            - Path=/users-ws/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1

        - id: create-user
          uri: lb://user-ws
          predicates:
            - Path=/users
          filters:
            - RemoveRequestHeader=Cookie

        - id: account-ws-checker
          uri: lb://account-ws
          predicates:
            - Path=/account/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.loadbalancer: DEBUG
#    com.netflix.discovery: DEBUG
