input {
  file {
    path => "/logs/users-ws.log"
    type => "users-ws-log"
    start_position => "beginning"
  }

  file {
    path => "/logs/albums-ws.log"
    type => "albums-ws-log"
    start_position => "beginning"
  }
}


output {

	if [type] == "users-ws-log" {
	
		elasticsearch {
			hosts => ["http://host.docker.internal:9200"]
			index => "users-ws-%{+YYYY.MM.dd}"
		}
	
	} else if [type] == "albums-ws-log" {
		
		elasticsearch {
			hosts => ["http://host.docker.internal:9200"]
			index => "albums-ws-%{+YYYY.MM.dd}"
		}		
	
	}
  
  stdout { codec => rubydebug }
}