spring:
  application:
    name: discoveryservice
  cloud:
    config:
      username: client
      password: 123456789
  config:
    import: "configserver:http://localhost:8012"

server:
  port: 8761

eureka:
#  instance:
#    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false